{% set name = "xarray-lmfit" %}
{% set version = "0.1.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray_lmfit-{{ version }}.tar.gz
  sha256: 7906b0ca64c35aaf2e661dd1a7cd8d3dfb836a9e4a23ab054d8e27d0972ba827

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - joblib >=1.4.2
    - lmfit >=1.3.2
    - numpy >=1.26.0
    - tqdm >=4.67.1
    - xarray >=2025.1.2

test:
  imports:
    - xarray_lmfit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kmnhan/xarray-lmfit
  summary: Fit lmfit models to xarray objects.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://xarray-lmfit.readthedocs.io/
  dev_url: https://github.com/kmnhan/xarray-lmfit

extra:
  recipe-maintainers:
    - kmnhan
