{% set name = "xarray-lmfit" %}
{% set version = "0.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray_lmfit-{{ version }}.tar.gz
  sha256: 8b9a63471ece9d35b62cfe4a69e58c4bb3f66d74dfedfb89f1cd97a09dfad9ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - joblib >=1.4.0
    - lmfit >=1.3.2
    - numpy >=1.26.0
    - tqdm >=4.66.2
    - xarray >=2024.10.0

test:
  imports:
    - xarray_lmfit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kmnhan/xarray-lmfit
  summary: Fit lmfit models to xarray objects.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://xarray-lmfit.readthedocs.io/
  dev_url: https://github.com/kmnhan/xarray-lmfit

extra:
  recipe-maintainers:
    - kmnhan
